export const GAME_CONFIG = {
    ROWS: 10,
    COLS: 9,
    COLORS_COUNT: 5,

    INITIAL_MOVES: 20,
    TARGET_SCORE: 5000,
    
    MIN_MATCH: 2,

    TILE_STEP: 100,
    TILE_WIDTH: 100,
    TILE_HEIGHT: 112,

    BOOSTER_BOMB_COUNT: 3,
    TELEPORT_COUNT: 5,
    SHUFFLE_COUNT: 3,

    TILES_FOR_BOMB: 5,
    TILES_FOR_ROCKET_H: 6,
    TILES_FOR_ROCKET_V: 7,
    TILES_FOR_DYNAMITE: 8,


    SCORE_MULT_STANDART: 10,
    SCORE_MULT_1: 35,
    SCORE_MULT_2: 80,
    
};
